### ISSUE TITLE
wuyi佬有考虑对野生bot的触发与使用进行优化吗

### ISSUE THREAD

**Issue by Rinco304** [KimigaiiWuyi/gsuidcore_psytest#2]
非官方bot不能发送按钮，进行测试和输入命令有点麻烦（如必须要emoji和文字一起发才可进行下一个指令），热门测试 功能也无法正常显示，所以来问一问大佬有没有对野生bot的使用优化计划😢

**Comment by KimigaiiWuyi** [comment]
本地已完成发送ABCD或1234即可提交答案的功能
本地已完成更多测试项目
不过可能还需要**一段时间**才会推送到本项目

不管怎么说，没有按钮的话确实是会比较麻烦
gscore对kook、dodo、telegram甚至米游社大别野这几个平台，都有较好的按钮支持，也可以尝试使用这几个平台

**Comment by KimigaiiWuyi** [comment]
基本框架已完成
